export const LOGIN_ACTION = {
    LOGIN_FIELD_CHANGE: "LOGIN_FIELD_CHANGE",
    LOGIN_SUBMIT: "LOGIN_SUBMIT",
    LOGIN_SET_TOKEN: "LOGIN_SET_TOKEN",
    LOGOUT: "LOGOUT",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGIN_SET_USER_DATA: "LOGIN_SET_USER_DATA"
};

export const ADMIN_ACTION = {
    SET_LIST_OF_REQUESTS_FOR_TAKE: "SET_LIST_OF_REQUESTS_FOR_TAKE",
    DELETE_REQUEST_FOR_TAKING: "DELETE_REQUEST_FOR_TAKING",
    SET_LIST_OF_REQUESTS_FOR_LEAVE: "SET_LIST_OF_REQUESTS_FOR_LEAVE",
    DELETE_REQUEST_FOR_LEAVING: "DELETE_REQUEST_FOR_LEAVING"
};

export const LOCATION_ACTION = {
    LOCATION_SET_CITIES: "LOCATION_SET_CITIES",
    LOCATION_SET_LOCATIONS: "LOCATION_SET_LOCATIONS",
    LOCATION_SET_PLACES: "LOCATION_SET_PLACES",
    LOCATION_SET_SELECTED_PLACE: "LOCATION_SET_SELECTED_PLACE",
    LOCATION_SET_SELECTED_CITY: "LOCATION_SET_SELECTED_CITY",
    LOCATION_SET_SELECTED_LOCATION: "LOCATION_SET_SELECTED_LOCATION",
    UPDATE_PLACE_STATE: "UPDATE_PLACE_STATE"
};

export const CALENDAR_ACTION = {
    CALENDAR_TOGGLE: "CALENDAR_TOGGLE",
    CALENDAR_SET_DAYS: "CALENDAR_SET_DAYS",
    CALENDAR_SET_BORROW: "CALENDAR_SET_BORROW",
    CALENDAR_SET_FREE: "CALENDAR_SET_FREE",
    CALENDAR_SET_SIMPLE: "CALENDAR_SET_SIMPLE"

};

export const PLACE_ACTION = {
    PLACE_SET_PLACE_DATA: "PLACE_SET_PLACE_DATA"
};